// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbtiogcqxtgzefbdrwqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidGlvZ2NxeHRnemVmYmRyd3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDM4MTksImV4cCI6MjA2NjU3OTgxOX0.SMYTpp7QeroAogoY50oWtesMoqvjFHr2nbx8n293giI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);